/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查（免鉴权） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            version: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 音色/模型/供应商/默认值与公告 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Config"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 供应商列表（api_key 永不下发） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Provider"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 保存供应商 API Key（服务端 AES-256-GCM 密文落盘） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        api_key: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 编辑供应商元数据（name/base_url/budget_group，自定义上游） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        base_url?: string;
                        budget_group?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 设为默认供应商 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导入会话列表（SQL 分页） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionPage"];
                    };
                };
            };
        };
        put?: never;
        /** 创建导入会话 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** 删除会话及其任务/音频（级联） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消会话内全部非终态任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出会话全部成品音频（流式 ZIP） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description zip stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量导入 TXT（multipart，多文件单事务，UTF-8/GBK 探测） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        files: string[];
                        session_id?: string;
                        session_name?: string;
                        voice?: string;
                        model?: string;
                        style?: string;
                    };
                };
            };
            responses: {
                /** @description 导入已受理，任务后台入队 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportResult"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/scoped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 签发短期 scoped 签名凭据（供 URL 场景：audio/events/preview，替代原始 token） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description audio:{task_id} | events:{channel} | preview:{voice_id} */
                        scope: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token: string;
                            expires_in: number;
                            scope: string;
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表（SQL 分页 + 状态/会话/搜索过滤） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    page_size?: number;
                    status?: components["schemas"]["TaskStatus"];
                    session_id?: string;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskPage"];
                    };
                };
            };
        };
        put?: never;
        /** 创建合成任务（提交即入队；超长文本智能分片） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情（含分片） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskDetail"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** 删除任务与音频文件 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重试失败任务（重切+重入队） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务音频（HTTP Range 流式播放/seek；token 经 query 或 Bearer） */
        get: {
            parameters: {
                query?: {
                    token?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description audio stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/wav": string;
                    };
                };
                /** @description partial content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单任务音频下载（attachment；token 经 query 或 Bearer） */
        get: {
            parameters: {
                query?: {
                    token?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description audio file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/wav": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 音色试听（302 重定向到官方 CDN 白名单；token 经 query 或 Bearer） */
        get: {
            parameters: {
                query?: {
                    token?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description redirect to CDN sample */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE 实时事件流（channel=session:{id}|task:{id}|providers；token 经 query 或 Bearer） */
        get: {
            parameters: {
                query: {
                    channel: string;
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream（DomainEvent，`type` 标签 JSON） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 引擎运行时统计（队列深度/worker/各 provider AIMD 窗口与熔断状态） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            queue_depth?: number;
                            workers?: number;
                            providers?: {
                                provider_id?: string;
                                group?: string;
                                window?: number;
                                inflight?: number;
                                open?: boolean;
                                retry_after_secs?: number | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Id: string;
        /** @enum {string} */
        TaskStatus: "pending" | "queued" | "synthesizing" | "merging" | "done" | "failed" | "cancelled";
        /** @enum {string} */
        ChunkStatus: "pending" | "inflight" | "done" | "failed";
        /** @enum {string} */
        SessionStatus: "active" | "completed" | "failed" | "cancelled";
        VoicePreset: {
            id: string;
            name: string;
            language: string;
            gender: string;
            style?: string;
            preview_url?: string;
        };
        ModelPreset: {
            id: string;
            name: string;
            description?: string;
        };
        Provider: {
            id: string;
            name: string;
            base_url: string;
            /** @enum {string} */
            kind: "xiaomi" | "custom";
            is_configured: boolean;
            is_default: boolean;
            budget_group?: string;
        };
        Config: {
            voices: components["schemas"]["VoicePreset"][];
            models: components["schemas"]["ModelPreset"][];
            providers: components["schemas"]["Provider"][];
            default_voice: string;
            default_model: string;
            chunk: components["schemas"]["ChunkSettings"];
            announcement?: string | null;
            stream_audio: boolean;
        };
        ChunkSettings: {
            context_window_tokens?: number;
            target_tokens?: number;
            hard_cap_tokens?: number;
        };
        Session: {
            id: components["schemas"]["Id"];
            name: string;
            status: components["schemas"]["SessionStatus"];
            total_tasks: number;
            done_tasks: number;
            failed_tasks: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        Task: {
            id: components["schemas"]["Id"];
            session_id?: components["schemas"]["Id"];
            title: string;
            status: components["schemas"]["TaskStatus"];
            voice: string;
            model: string;
            style?: string | null;
            total_chars?: number;
            total_tokens?: number;
            total_chunks: number;
            done_chunks: number;
            failed_chunks: number;
            duration_ms?: number | null;
            error?: string | null;
            has_audio: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        Chunk: {
            id: components["schemas"]["Id"];
            task_id: components["schemas"]["Id"];
            seq: number;
            text?: string;
            token_estimate: number;
            status: components["schemas"]["ChunkStatus"];
            retry_count: number;
            duration_ms?: number | null;
            error?: string | null;
        };
        TaskDetail: components["schemas"]["Task"] & {
            content?: string;
            chunks?: components["schemas"]["Chunk"][];
        };
        CreateTaskRequest: {
            title: string;
            content: string;
            voice: string;
            /** @default mimo-v2.5-tts */
            model: string;
            style?: string | null;
            provider_id?: string | null;
            session_id?: components["schemas"]["Id"];
            /** @default 0 */
            priority: number;
        };
        TaskPage: {
            data: components["schemas"]["Task"][];
            total: number;
            page: number;
            page_size: number;
        };
        SessionPage: {
            data: components["schemas"]["Session"][];
            total: number;
            page: number;
            page_size: number;
        };
        ImportResult: {
            session_id: components["schemas"]["Id"];
            files_received: number;
            tasks_created: number;
            rejected?: string[];
        };
    };
    responses: {
        /** @description 结构化错误 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                    /** @enum {string} */
                    code: "NOT_FOUND" | "INVALID_INPUT" | "UNAUTHORIZED" | "RATE_LIMITED" | "CONTENT_BLOCKED" | "CONTEXT_OVERFLOW" | "CONFLICT" | "INTERNAL";
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
